// Generated by gencpp from file tutorial_python/Person.msg
// DO NOT EDIT!


#ifndef TUTORIAL_PYTHON_MESSAGE_PERSON_H
#define TUTORIAL_PYTHON_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial_python
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : first_name()
    , last_name()
    , age(0)  {
    }
  Person_(const ContainerAllocator& _alloc)
    : first_name(_alloc)
    , last_name(_alloc)
    , age(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _first_name_type;
  _first_name_type first_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _last_name_type;
  _last_name_type last_name;

   typedef uint8_t _age_type;
  _age_type age;





  typedef boost::shared_ptr< ::tutorial_python::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_python::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::tutorial_python::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::tutorial_python::Person > PersonPtr;
typedef boost::shared_ptr< ::tutorial_python::Person const> PersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_python::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_python::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial_python::Person_<ContainerAllocator1> & lhs, const ::tutorial_python::Person_<ContainerAllocator2> & rhs)
{
  return lhs.first_name == rhs.first_name &&
    lhs.last_name == rhs.last_name &&
    lhs.age == rhs.age;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial_python::Person_<ContainerAllocator1> & lhs, const ::tutorial_python::Person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial_python

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorial_python::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_python::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_python::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_python::Person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_python::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_python::Person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_python::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e284f48db143ad4a2296917c51a4a73e";
  }

  static const char* value(const ::tutorial_python::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe284f48db143ad4aULL;
  static const uint64_t static_value2 = 0x2296917c51a4a73eULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_python::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_python/Person";
  }

  static const char* value(const ::tutorial_python::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_python::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string first_name\n"
"string last_name\n"
"uint8 age\n"
;
  }

  static const char* value(const ::tutorial_python::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_python::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first_name);
      stream.next(m.last_name);
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_python::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_python::Person_<ContainerAllocator>& v)
  {
    s << indent << "first_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.first_name);
    s << indent << "last_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.last_name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_PYTHON_MESSAGE_PERSON_H
